[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_solana = "6bNvL8etdpkopaHnukGpExuqbCaqkFhd3Psh46KsdhjN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/outsider/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
