[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solva = "GuvvxMUBDziMyyB2fy7XoUy7cLE5mHQiBNwPzHHHDtSg"

[programs.devnet]
solva = "GuvvxMUBDziMyyB2fy7XoUy7cLE5mHQiBNwPzHHHDtSg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
