[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
first_solana_contract = "33y4yjhenw3rbSvzb3NoMktAmMzdMh9FfGbuEgKuU8qK"

[programs.devnet]
first_solana_contract = "33y4yjhenw3rbSvzb3NoMktAmMzdMh9FfGbuEgKuU8qK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
