[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solva = "DghdsNx3fCwuReK5zMoixhFcMQk7uhYm81EojrwQVex1"

[programs.devnet]
solva = "DghdsNx3fCwuReK5zMoixhFcMQk7uhYm81EojrwQVex1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# wallet = "/Users/outsider987/.config/solana/id.json"
wallet = "/home/outsider/.config/solana/id.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
